Repository spryker-shop/b2c-demo-shop, pull requests merged in 2023-06, with the labels that each got.

#242 CC-25629 Updated Node.js to v18.
  .github/workflows/ci.yml
  .nvmrc
  composer.json
  deploy.aop-b2c-testing.yml
  deploy.aop-demoshop-b2c.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.yml
  frontend/configs/development.js
  package-lock.json
  package.json
  tsconfig.json
Labels: improvement

#205 CC-16903 Adjusted login mechanism for Backoffice and Merchant Portal.
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Client/SecurityBlocker/SecurityBlockerDependencyProvider.php
  src/Pyz/Zed/ErrorHandler/ErrorHandlerConfig.php
  src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
Labels: bug, ready-for-release

#243 CC-23397: Added resource relationship support for Backend API.
  src/Pyz/Glue/DocumentationGeneratorApi/DocumentationGeneratorApiDependencyProvider.php
Labels: bug, request-review

#252 CC-29493 Added the robotframework-suite-tests repository to dependencies
  composer.json
  composer.lock
Labels: ready-for-release, dependencies, improvement

#259 CC-29685: Adjusted installation configuration to fix an issue on AT store.
  config/install/docker.yml
Labels: bug, ready-for-release

#264 CC-21301: Fixed invalid checkout payment
  composer.json
  composer.lock
  src/Pyz/Zed/CartCode/CartCodeDependencyProvider.php
Labels: bug, ready-for-release
