Repository spryker-shop/b2c-demo-shop, pull requests merged in 2023-12, with the labels that each got.

#398 CC-32034 Fixed Robot package sync issue.
  .dockersyncignore
Labels: bug

#406 CC-31983 Fixed Agent bar
  package-lock.json
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.scss
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.twig
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/customer-list/customer-list.twig
  src/Pyz/Yves/AgentWidget/Theme/default/components/organisms/agent-control-bar/agent-control-bar.scss
  src/Pyz/Yves/AgentWidget/Theme/default/components/organisms/agent-control-bar/agent-control-bar.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/button/button.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/jumbotron-slider/jumbotron-slider.scss
  src/Pyz/Yves/ShopUi/Theme/default/styles/basics/_grid.scss
Labels: bug

#407 CC-32131 Fixed merchant portal and Product configurator build for CI acceptance configuration files.
  config/install/docker.ci.acceptance.robot.yml
  deploy.ci.acceptance.mariadb.robot.yml
Labels: bug

#402 CC-31773 Fixed issue with missing shipment price on Order Details page.
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/summary-sidebar/summary-sidebar.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/summary/summary.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail-table/order-detail-table.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/shipment-information/index.ts
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/shipment-information/shipment-information.scss
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/shipment-information/shipment-information.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/components/molecules/customer-reorder-form/customer-reorder-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-bar/action-bar.scss
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: bug, ready-for-release

#408 CC-32150 Removed redundant services from robot deploy file.
  deploy.ci.acceptance.mariadb.robot.yml
Labels: ready-for-release, request-review, improvement

#410 CC-32149 Fixed logo displaying in Safari browser.
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/footer-logo/footer-logo.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/footer-logo/footer-logo.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/logo/logo.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/logo/logo.twig
Labels: bug

#412 CC-32127 Cookies SameSite Lax integration.
  config/Shared/config_default.php
Labels: bug, ready-for-release

#414 CC-32217 Fixed Bundle items stock import data.
  data/import/common/common/product_stock.csv
Labels: bug, ready-for-release

#419 CC-18186 Fixed color selector on PDP.
  composer.lock
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-carousel/product-carousel.twig
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.twig
Labels: bug
