Repository spryker-shop/b2c-demo-shop, pull requests merged in 2023-10, with the labels that each got.

#318 SUPESC-783 Added missing integration for storing expenses in Quote.
  src/Pyz/Zed/Quote/QuoteConfig.php
Labels: bug, ready-for-release

#321 CC-31482 Update the oryx-for-zed dependency
  package-lock.json
  package.json
Labels: dependencies

#327 CC-29874 Updated `npm` dependencies.
  composer.lock
  package-lock.json
  package.json
Labels: dependencies

#323 CC-31029 Fixed exception for deactivated products in cart integration.
  composer.json
  composer.lock
  src/Pyz/Yves/CartPage/CartPageDependencyProvider.php
Labels: bug

#331 SUPESC-780 Fixed failing automated tests on local environment.
  deploy.dev.yml
  tests/PyzTest/Yves/Application/Presentation/Controller/HomepageCest.php
  tests/PyzTest/Yves/Application/_support/ApplicationPresentationTester.php
  tests/PyzTest/Yves/Application/codeception.yml
  tests/PyzTest/Zed/NavigationGui/Presentation/NavigationCRUDCest.php
  tests/PyzTest/Zed/NavigationGui/_support/NavigationGuiPresentationTester.php
  tests/PyzTest/Zed/Product/Business/ProductAbstractManagerTest.php
  tests/PyzTest/Zed/Product/Business/ProductConcreteManagerTest.php
  tests/PyzTest/Zed/ProductRelation/Presentation/ProductRelationCreateRelationCest.php
  tests/PyzTest/Zed/ProductRelation/_support/ProductRelationPresentationTester.php
Labels: bug, ready-for-release

#337 CC-31574 Update npm dependencies
  package-lock.json
Labels: dependencies

#346 CC-31636 Add missing image set relationship to concrete product.
  composer.json
  composer.lock
  src/Pyz/Glue/GlueBackendApiApplicationGlueJsonApiConventionConnector/GlueBackendApiApplicationGlueJsonApiConventionConnectorDependencyProvider.php
Labels: bug, request-review

#332 FRW-6379: Synchronize cors-allow-origin property
  deploy.dev.yml
Labels: bug, ready-for-release

#352 FRW-6504 Adjusted Data Exchange API configuration file.
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: bug

#355 CC-31686 Docker CI fix integration.
  config/Shared/config_default-docker.ci.php
Labels: ready-for-release

#353 CC-31676 Updated tooling configuration for NPM evaluator.
  composer.lock
  tooling.yml
Labels: bug, ready-for-release
