Repository spryker-shop/b2c-demo-shop, pull requests merged in 2023-03, with the labels that each got.

#182 CC-26078: Add robot test
  .github/workflows/ci.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
Labels: ready-for-release

#190 CC-25744 Fixed missing number formatting on Sales page.
  src/Pyz/Yves/ExampleProductSalePage/Controller/SaleController.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageFactory.php
Labels: bug, request-review

#186 SUPESC-603 Fixed product category order overriding during data import
  src/Pyz/Zed/DataImport/Business/Model/ProductAbstract/ProductAbstractHydratorStep.php
Labels: bug

#189 CC-26185 CC-26347: Fixed scheduled prices concatenation for MariaDB.
  composer.lock
  config/install/docker.ci.acceptance.yml
Labels: bug, ready-for-release

#191 SUPESC-618 Added customer access publisher trigger plugin
  composer.lock
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: bug, ready-for-release

#200 SUPESC-606 Fixed filtering by stores in Availability Notifications.
  composer.json
  composer.lock
  config/Shared/config_default.php
  deploy.aop-b2c-testing.yml
  deploy.aop-demoshop-b2c.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.yml
  deploy.yml
Labels: bug, ready-for-release

#201 SUPESC-727 Replaced discount product label conditions with IN and NOT IN comparators.
  composer.json
  composer.lock
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: bug, ready-for-release

#203 CC-23635 Added optimisations to handle product bundle on cart page.
  composer.json
  composer.lock
  src/Pyz/Zed/PriceCartConnector/PriceCartConnectorConfig.php
Labels: bug, ready-for-release

#197 SDK-1815 cleanup
  composer.lock
  src/Pyz/Client/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Glue/Log/LogDependencyProvider.php
  src/Pyz/Service/Flysystem/FlysystemDependencyProvider.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Yves/Log/LogDependencyProvider.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
  src/Pyz/Zed/Flysystem/FlysystemDependencyProvider.php
Labels: improvement

#192 CC-16906 Adjusted session & token validation.
  composer.json
  composer.lock
  config/Zed/cronjobs/jenkins.php
  src/Orm/Zed/CustomerStorage/Persistence/SpyCustomerInvalidatedStorage.php
  src/Orm/Zed/CustomerStorage/Persistence/SpyCustomerInvalidatedStorageQuery.php
  src/Pyz/Client/Oauth/OauthDependencyProvider.php
  src/Pyz/Client/RabbitMq/RabbitMqConfig.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/Customer/Persistence/Propel/Schema/spy_customer.schema.xml
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Queue/QueueDependencyProvider.php
  src/Pyz/Zed/Synchronization/SynchronizationDependencyProvider.php
Labels: ready-for-release
