Repository spryker-shop/b2c-demo-shop, pull requests merged in 2023-07, with the labels that each got.

#272 CC-29960: Added missing mail sender.
  deploy.spryker-b2cintt.yml
Labels: bug, request-architecture-review

#273 CC-29918 Fixed AddressForm's city field input type.
  composer.json
  composer.lock
Labels: bug, ready-for-release

#275 CC-29931 Update Sales module
  composer.json
  composer.lock
Labels: bug, request-review

#274 CC-29647 Fixed FE Yves commands.
  .prettierrc.js
  composer_back.json
  frontend/libs/command-line-parser.js
  frontend/libs/formatter.js
  frontend/settings.js
  package-lock.json
  package.json
Labels: bug

#276 CC-24090: Fixed checkout address form on submit action.
  composer.json
  composer.lock
Labels: bug, request-review

#277 CC-30090 Adjust CORS configuration for demo shops GLUE APIs
  deploy.spryker-b2cintt.yml
Labels: ready-for-release

#278 CC-16486 Bugfixes integration
  composer.json
  composer.lock
  src/Pyz/Client/ProductReview/ProductReviewDependencyProvider.php
Labels: bug

#279 CC-30078 Fixed users search for agent
  composer.json
  composer.lock
Labels: bug

#285 FRW-1992 and FRW-2313 Integration
  composer.json
  composer.lock
Labels: bug, request-review

#287 FRW-2432 FRW-2377 Fixed Oauth token saving if it already exists. Fixed disabling CORS headers.
  composer.json
  composer.lock
Labels: bug

#284 CC-25992: Adjusted login mechanism for agent and customer.
  composer.lock
  src/Pyz/Yves/SecurityBlockerPage/SecurityBlockerPageConfig.php
Labels: bug
