Repository spryker-shop/b2c-demo-shop, pull requests merged in 2023-11, with the labels that each got.

#361 CC-31725 Update npm dependencies
  composer.lock
  package-lock.json
  package.json
Labels: bug, dependencies

#359 FRW-998 updated PHP version
  .github/workflows/ci.yml
  .scrutinizer.yml
  README.md
  composer.json
  composer.lock
  deploy.aop-b2c-testing.yml
  deploy.aop-consultant-b2c.yml
  deploy.aop-demoshop-b2c.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store.yml
  deploy.ci.api.mariadb.dynamic-store.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store.yml
  deploy.ci.functional.mariadb.dynamic-store.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.spryker-dynamicstore.yml
  deploy.yml
  phpcs.xml
  src/Pyz/Yves/ProductReviewWidget/Form/ProductReviewForm.php
  src/Pyz/Zed/Installer/InstallerDependencyProvider.php
  tests/PyzTest/Yves/Checkout/Process/Steps/AddressStepTest.php
Labels: improvement

#364 CC-31755 `main-overlay` and `main-popup` components integration.
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/shipment/shipment.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/summary/summary.twig
  src/Pyz/Yves/DateTimeConfiguratorPageExample/Theme/default/views/options-list/options-list.twig
  src/Pyz/Yves/ProductConfigurationCartWidget/Theme/default/views/cart-item-configuration/cart-item-configuration.twig
  src/Pyz/Yves/ProductReviewWidget/Theme/default/components/molecules/new-review-form/new-review-form.twig
  src/Pyz/Yves/ProductReviewWidget/Theme/default/components/organisms/review-summary/review-summary.twig
  src/Pyz/Yves/ProductReviewWidget/Theme/default/views/pdp-review/pdp-review.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/button/button.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon/icon.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/collapsible-list/collapsible-list.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-top-mobile/navigation-top-mobile.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/popup/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/popup/popup.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/search-form/search-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search-extended.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/navigation-top/navigation-top.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/navigation-top/navigation-top.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.twig
  src/Pyz/Yves/ShopUi/Theme/default/styles/settings/_z-index.scss
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig
Labels: improvement

#367 CC-31790 Updated navigation node demo data.
  data/import/common/common/navigation_node.csv
Labels: ready-for-release

#368 CC-31784 Fixed preselected address state for multiple addresses at checkout
  composer.json
  composer.lock
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
Labels: bug

#371 FRW-6810 Fixed config file for DDE API
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: bug

#372 CC-31780 Fixed caching of categories in discounts.
  composer.json
  composer.lock
Labels: bug

#375 CC-31681 Adjusted warehouse allocation to assign warehouse with the largest stock regardless of item quantity.
  composer.json
  composer.lock
Labels: bug, request-architecture-review

#374 CC-25879 Decreased memory usage in product data import.
  src/Pyz/Zed/DataImport/Business/DataImportBusinessFactory.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepository.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepositoryInterface.php
  src/Pyz/Zed/DataImport/Business/Model/ProductConcrete/ProductConcreteAttributesUniqueCheckStep.php
  src/Pyz/Zed/DataImport/DataImportConfig.php
Labels: bug

#377 CC-31810 Fixed header dropdowns
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.scss
Labels: bug, ready-for-release

#370 CC-31600: Fixed warehouse user assignment validation
  composer.json
  composer.lock
Labels: bug

#384 Bulk bugfixes integration
  composer.json
  composer.lock
  tests/PyzTest/Glue/ProductConfigurations/RestApi/Fixtures/ProductConfigurationsRestApiFixtures.php
Labels: bug

#387 CC-29261 Updated product configuration API validation and CMS API tests.
  composer.json
  composer.lock
Labels: bug
