Repository spryker-shop/b2c-demo-shop, pull requests merged in 2024-05, with the labels that each got.

#472 FRW-7507 Upgraded Jenkins version.
  .git.docker
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store.yml
  deploy.ci.api.mariadb.dynamic-store.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store.yml
  deploy.ci.functional.mariadb.dynamic-store.yml
  deploy.ci.functional.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.scos2-b2c.yml
  deploy.spryker-dynamicstore.yml
  deploy.spryker-scosb2c.yml
  deploy.yml
Labels: improvement

#487 CC-33312: Added E2E Cypress UI tests into CI process for Dynamic multistore.
  .github/workflows/ci.yml
  composer.lock
  config/install/docker.ci.acceptance.dynamic-store.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store.cypress.yml
Labels: ready-for-release

#493 CC-33309: Added the check to run on the merge to the master branch.
  .github/workflows/robot-ui-e2e-tests.yml
Labels: robot-regression-ui-e2e

#496 FRW-7201 Integration
  composer.lock
  data/import/common/common/glossary.csv
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: improvement, robot-regression-ui-e2e
