Repository spryker-shop/b2c-demo-shop, pull requests merged in 2024-06, with the labels that each got.

#501 CC-33768: Added fixes for the "Robot Regression UI E2E"
  .github/workflows/robot-ui-e2e-tests.yml
Labels: improvement, robot-regression-ui-e2e

#503 CC-33794: Fix behavior while submit quantity on async cart
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.twig
Labels: ready-for-release, robot-regression-ui-e2e

#502 Enabled cypress tests for epic - Async Cart reload feature.
  composer.lock
  package-lock.json
Labels: ready-for-release, robot-regression-ui-e2e

#505 CC-33310: Introduced the workflow to auto-merge the latest release to the "master-deploy" branch.
  .github/workflows/up-merge-latest-release-to-master-deploy.yml
Labels: request-review, improvement
