Repository spryker-shop/b2c-demo-shop, pull requests merged in 2024-08, with the labels that each got.

#520 ACP-3589: Sales Payment details integration
  composer.json
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: skip-robot-regression-ui-e2e

#515 ACP-3544: Added MP
  deploy.aop-demoshop-b2c.yml
Labels: improvement, skip-robot-regression-ui-e2e

#524 ACP-3580: Payone ACP App: Klarna Payment Method
  composer.lock
  src/Pyz/Zed/Payment/PaymentConfig.php
Labels: ready-for-release, robot-regression-ui-e2e

#530 FRW-8868 Hackhaton CI.
  .github/workflows/ci.yml
Labels: skip-robot-regression-ui-e2e

#532 FRW-8938 Integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Service/Flysystem/FlysystemDependencyProvider.php
Labels: skip-robot-regression-ui-e2e, hackathon
