Repository spryker-shop/b2c-demo-shop, pull requests merged in 2024-10, with the labels that each got.

#552 ACP-3930: changed OMS to ForeignPaymentB2CStateMachine01
  config/Shared/config_default.php
Labels: robot-regression-ui-e2e

#553 FWR-9121 Fixed broken robot test
  composer.json
  composer.lock
  src/Pyz/Zed/DynamicEntity/DynamicEntityDependencyProvider.php
Labels: skip-robot-regression-ui-e2e

#542 FRW-8878 Integrated router performance issue fix.
  composer.lock
  src/Pyz/Zed/Router/RouterConfig.php
Labels: robot-regression-ui-e2e

#549 CC-34390 Discount Rule based on customer order counter Feature integration
  composer.json
  composer.lock
  data/import/common/AT/discount_store.csv
  data/import/common/DE/discount_store.csv
  data/import/common/US/discount_store.csv
  data/import/common/common/discount.csv
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: ready-for-release, improvement, robot-regression-ui-e2e

#555 FRW-9030 SUPESC Integrations
  composer.lock
Labels: robot-regression-ui-e2e

#556 FRW-7443 Store Context integration.
  composer.lock
  data/import/common/AT/store_context.csv
  data/import/common/DE/store_context.csv
  data/import/common/EU/store_context.csv
  data/import/common/US/store_context.csv
  data/import/common/commerce_setup_import_config_EU.yml
  data/import/common/commerce_setup_import_config_US.yml
  data/import/common/minimal.yml
  data/import/local/full_EU.yml
  data/import/local/full_US.yml
  data/import/production/full_EU.yml
  data/import/production/full_US.yml
  src/Pyz/Client/Store/StoreDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Store/StoreDependencyProvider.php
  src/Pyz/Zed/StoreContext/Persistence/Propel/Schema/spy_store_context.schema.xml
  src/Pyz/Zed/StoreGui/StoreGuiDependencyProvider.php
Labels: robot-regression-ui-e2e

#559 FRW-9030 Integrations part 4
  composer.json
  composer.lock
Labels: robot-regression-ui-e2e

#558 FRW-8761 Adjusted configuration
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: skip-robot-regression-ui-e2e

#554 FRW-9030 Integrations part 1
  composer.lock
Labels: robot-regression-ui-e2e

#565 FRW-9164 Added extension point to the VariantTable.
  composer.lock
Labels: skip-robot-regression-ui-e2e

#564 FRW-9030 Integrations part 5
  composer.lock
  src/Pyz/Zed/ProductStorage/Persistence/ProductStoragePersistenceFactory.php
Labels: robot-regression-ui-e2e

#566 FRW-1633 Integrations
  .git.docker
  composer.lock
Labels: robot-regression-ui-e2e

#573 CC-34672 Collapsible category tree integraton
  composer.json
  composer.lock
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig
Labels: ready-for-release, robot-regression-ui-e2e

#572 CC-34259: Product comparison integration
  composer.json
  composer.lock
  data/import/common/common/glossary.csv
  src/Pyz/Yves/ProductComparisonPage/Theme/default/components/molecules/comparison-link/comparison-link.twig
  src/Pyz/Yves/ProductComparisonPage/Theme/default/components/molecules/comparison-table/comparison-table.scss
  src/Pyz/Yves/ProductComparisonPage/Theme/default/components/molecules/comparison-table/index.ts
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-configurator/product-configurator.twig
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-top-mobile-item/navigation-top-mobile-item.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-top-mobile/navigation-top-mobile.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/navigation-top/navigation-top.twig
Labels: ready-for-release, robot-regression-ui-e2e

#574 FRW-9170: Integration
  composer.lock
Labels: robot-regression-ui-e2e

#569 Analytics integration
  composer.json
  composer.lock
  config/Zed/navigation.xml
Labels: skip-robot-regression-ui-e2e

#575 FRW-6475 Fixed product label localized attributes for DS.
  composer.lock
  config/install/docker.ci.functional.yml
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: bug, robot-regression-ui-e2e

#577 CC-34696: CC-34695: integrations.
  composer.json
  composer.lock
Labels: robot-regression-ui-e2e

#578 CC-34707 Accessibility issue wrong color on State Machine button in Backoffice
  composer.json
  composer.lock
Labels: skip-robot-regression-ui-e2e

#576 Release 202410.0
  composer.json
  composer.lock
  config/install/docker.ci.functional.yml
  data/import/common/common/glossary.csv
  deploy.aop-b2c-testing.yml
  deploy.aop-consultant-b2c.yml
  deploy.aop-demoshop-b2c.yml
  deploy.scos2-b2c.yml
  deploy.spryker-dynamicstore.yml
  deploy.spryker-scosb2c.yml
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  tests/PyzTest/Yves/Checkout/Process/Steps/SuccessStepTest.php
Labels: robot-regression-ui-e2e

#583 FRW-9241 Adjusted installation configs.
  config/install/ci.yml
  config/install/development.yml
  config/install/testing.yml
Labels: bug, robot-regression-ui-e2e

#584 CC-34246 Upgraded docker/sdk version.
  .git.docker
Labels: bug, skip-robot-regression-ui-e2e

#582 CC-34246 Added strict transport security headers to the static content.
  .git.docker
Labels: bug, robot-regression-ui-e2e
