Repository spryker-shop/b2c-demo-shop, pull requests merged in 2025-04, with the labels that each got.

#669 CC-22722: Order Sequence Generation integration
  composer.lock
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: improvement, run-latest-ci, run-functional-ci, run-ui-ci

#671 Integration: FRW-9444, FRW-9438
  composer.lock
Labels: run-latest-ci, run-static-ci

#673 CC-26244: [Performance] Quote is validated twice in Yves CartController
  composer.lock
  src/Pyz/Yves/CartPage/CartPageConfig.php
Labels: bug, run-static-ci, run-ui-ci

#678 CC-34245 bootstrap upgrade integration
  composer.lock
  package-lock.json
  package.json
Labels: run-latest-ci

#677 CC-35490 Fixed flaky CMS page test.
  tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiCreatePageCest.php
  tests/PyzTest/Zed/CmsGui/_support/CmsGuiPresentationTester.php
Labels: bug, run-compatibility-ci, run-static-ci

#679 CC-35103 Add P&S into destructive deployment.
  config/install/destructive.yml
Labels: bug, run-static-ci, run-npm-ci
