Repository spryker-shop/b2c-demo-shop, pull requests merged in 2025-08, with the labels that each got.

#765 CC-36115 Integrated bugfixes.
  composer.lock
Labels: run-latest-ci

#766 FRW-10782 Upgraded MFA modules version.
  composer.lock
Labels: improvement, run-latest-ci, run-static-ci, run-ui-ci, run-npm-ci

#761 CC-36099 tests for table filters
  composer.lock
  package-lock.json
Labels: run-ui-ci

#772 CC-36139 Fixing flickery tests.
  composer.lock
Labels: run-ui-ci

#779 SUPESC-864 Switching a discount's type doesn't handle the associated voucher codes.
  composer.lock
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: run-latest-ci

#780 CC-35970: Flaky CI. Data Import discount voucher failed
  src/Pyz/Zed/DataImport/Business/Model/DiscountVoucher/DiscountVoucherWriterStep.php
Labels: run-functional-ci

#781 CC-35421: Text alternatives integration
  composer.lock
  data/import/common/common/product_image.csv
  data/import/common/common/product_set.csv
  src/Pyz/Shared/ProductImage/ProductImageConfig.php
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.twig
  src/Pyz/Yves/ProductSetListPage/Theme/default/views/set-list/set-list.twig
  src/Pyz/Yves/ProductSetWidget/Theme/default/components/organisms/product-set-details/product-set-details.twig
  src/Pyz/Zed/DataImport/Business/DataImportBusinessFactory.php
  src/Pyz/Zed/DataImport/Business/Model/ProductImage/Writer/ProductImagePropelDataSetWriter.php
  src/Pyz/Zed/DataImport/Business/Model/ProductSet/ProductSetImageExtractorStep.php
  src/Pyz/Zed/DataImport/Business/Model/ProductSet/ProductSetImageLocalizedAttributesExtractorStep.php
  src/Pyz/Zed/DataImport/Business/Model/ProductSet/ProductSetWriterStep.php
  src/Pyz/Zed/ProductPageSearch/ProductPageSearchDependencyProvider.php
Labels: run-functional-ci, run-static-ci, run-ui-ci

#789 ACP-5354: Algolia: global search to CMS and docs integration
  composer.lock
  config/Shared/config_default.php
  config/Zed/cronjobs/jenkins.php
  src/Pyz/Client/Catalog/CatalogDependencyProvider.php
  src/Pyz/Client/CmsPageSearch/CmsPageSearchDependencyProvider.php
  src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-functional-ci, run-static-ci, run-ui-ci

#788 FRW-10554 Reduce the number of CI jobs
  .github/workflows/ci.yml
  deploy.ci.acceptance.postgres.dynamic-store-off.cypress.yml
Labels: improvement, run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-static-ci, run-ui-ci, run-npm-ci
