Repository spryker-shop/b2c-demo-shop, pull requests merged in 2025-05, with the labels that each got.

#684 CC-35650 April 2025 integrations.
  composer.lock
  tests/PyzTest/Yves/Checkout/Process/Steps/ShipmentStepTest.php
Labels: run-latest-ci, run-static-ci, run-npm-ci

#692 FRW-10406 Integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  config/Zed/cronjobs/jenkins.php
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/Sitemap/SitemapDependencyProvider.php
Labels: enhancement, run-functional-ci, run-static-ci

#693 CC-35509 Remove weekly CI and add run CI on commit to master.
  .github/actions/job-slack-notifications/action.yml
  .github/actions/scheduled-job-slack-notifications/action.yml
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: run-latest-ci, run-compatibility-ci

#698 CC-35509 Remove label check at static validation ci job.
  .github/workflows/ci.yml
Labels: improvement, run-latest-ci, run-compatibility-ci

#703 CC-35775 Remove obsolete CI jobs.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: run-latest-ci, run-compatibility-ci

#696 SUPESC-899 svg sprite asset generation integration
  .gitignore
  composer.lock
  frontend/configs/development.js
  frontend/libs/icon-sprite-extractor.js
  frontend/settings.js
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon/icon.twig
Labels: run-latest-ci

#708 CC-35103 Added Apply Scheduled Price and P&S into destructive deployment.
  config/install/destructive.yml
Labels: bug
