Repository spryker-shop/b2c-demo-shop, pull requests merged in 2025-07, with the labels that each got.

#721 FRW-901 Integrations.
  composer.lock
Labels: run-latest-ci, run-ui-ci

#724 FRW-10501 Integration.
  composer.lock
Labels: run-latest-ci, run-ui-ci

#731 CC-35846: Added timezone to Order Table filters.
  composer.lock
  src/Pyz/Zed/Store/StoreDependencyProvider.php
Labels: request-review, run-static-ci

#728 FRW-10720 Updated dependencies
  composer.json
  composer.lock
  src/Pyz/Zed/Application/ApplicationDependencyProvider.php
  src/Pyz/Zed/Twig/TwigDependencyProvider.php
  tests/PyzTest/Yves/Checkout/Process/Steps/SummaryStepTest.php
  tests/PyzTest/Zed/Console/_data/cli_sandbox/config/Shared/config_default.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCaptureFailedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCapturedMessageCest.php
Labels: improvement, run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-static-ci, run-ui-ci, run-npm-ci

#730 FRW-9059 MFA Integration
  composer.lock
  config/Shared/config_default-ci.php
  config/Shared/config_default-docker.dev.php
  config/Shared/config_default.php
  data/import/common/AT/cms_block_store.csv
  data/import/common/DE/cms_block_store.csv
  data/import/common/US/cms_block_store.csv
  data/import/common/common/cms_block.csv
  data/import/common/common/glossary.csv
  frontend/settings.js
  package-lock.json
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyCustomerMultiFactorAuth.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyCustomerMultiFactorAuthCodes.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyCustomerMultiFactorAuthCodesAttempts.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyCustomerMultiFactorAuthCodesAttemptsQuery.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyCustomerMultiFactorAuthCodesQuery.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyCustomerMultiFactorAuthQuery.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyUserMultiFactorAuth.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyUserMultiFactorAuthCodes.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyUserMultiFactorAuthCodesAttempts.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyUserMultiFactorAuthCodesAttemptsQuery.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyUserMultiFactorAuthCodesQuery.php
  src/Orm/Zed/MultiFactorAuth/Persistence/SpyUserMultiFactorAuthQuery.php
  src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php
  src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php
  src/Pyz/Glue/GlueStorefrontApiApplication/GlueStorefrontApiApplicationDependencyProvider.php
  src/Pyz/Glue/MultiFactorAuth/MultiFactorAuthConfig.php
  src/Pyz/Glue/MultiFactorAuth/MultiFactorAuthDependencyProvider.php
  src/Pyz/Shared/GlueBackendApiApplicationAuthorizationConnector/GlueBackendApiApplicationAuthorizationConnectorConfig.php
  src/Pyz/Shared/GlueStorefrontApiApplicationAuthorizationConnector/GlueStorefrontApiApplicationAuthorizationConnectorConfig.php
  src/Pyz/Yves/AgentPage/AgentPageDependencyProvider.php
  src/Pyz/Yves/CustomerPage/CustomerPageDependencyProvider.php
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/customer-navigation/customer-navigation.twig
  src/Pyz/Yves/CustomerPage/Theme/default/templates/page-layout-login/page-layout-login.twig
  src/Pyz/Yves/Form/FormDependencyProvider.php
  src/Pyz/Yves/MultiFactorAuth/MultiFactorAuthDependencyProvider.php
  src/Pyz/Yves/MultiFactorAuth/Theme/default/components/molecules/multi-factor-authentication-handler/multi-factor-authentication-handler.twig
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Yves/ShopUi/Theme/default/resources/form/form.twig
  src/Pyz/Zed/Customer/CustomerDependencyProvider.php
  src/Pyz/Zed/Form/FormDependencyProvider.php
  src/Pyz/Zed/Gui/GuiDependencyProvider.php
  src/Pyz/Zed/Mail/MailDependencyProvider.php
  src/Pyz/Zed/MultiFactorAuth/MultiFactorAuthDependencyProvider.php
  src/Pyz/Zed/SecurityGui/SecurityGuiConfig.php
  src/Pyz/Zed/SecurityGui/SecurityGuiDependencyProvider.php
  tests/PyzTest/Glue/MultiFactorAuth/BackendApi/Fixtures/MultiFactorAuthBackendApiFixtures.php
  tests/PyzTest/Glue/MultiFactorAuth/BackendApi/MultiFactorAuthBackendApiCest.php
  tests/PyzTest/Glue/MultiFactorAuth/RestApi/Fixtures/MultiFactorAuthRestApiFixtures.php
  tests/PyzTest/Glue/MultiFactorAuth/RestApi/MultiFactorAuthRestApiCest.php
  tests/PyzTest/Glue/MultiFactorAuth/StorefrontApi/Fixtures/MultiFactorAuthStorefrontApiFixtures.php
  tests/PyzTest/Glue/MultiFactorAuth/StorefrontApi/MultiFactorAuthStorefrontApiCest.php
  tests/PyzTest/Glue/MultiFactorAuth/_support/MultiFactorAuthBackendApiTester.php
  tests/PyzTest/Glue/MultiFactorAuth/_support/MultiFactorAuthRestApiTester.php
  tests/PyzTest/Glue/MultiFactorAuth/_support/MultiFactorAuthStorefrontApiTester.php
  tests/PyzTest/Glue/MultiFactorAuth/codeception.yml
  tests/PyzTest/Yves/Customer/Presentation/CustomerLoginCest.php
  tests/PyzTest/Yves/Customer/Presentation/CustomerLogoutCest.php
  tests/PyzTest/Zed/TestifyBackendApi/codeception.dynamic.fixtures.yml
Labels: enhancement, run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-static-ci, run-ui-ci, run-npm-ci

#732 FRW-9059 MFA Integration
  composer.lock
Labels: run-latest-ci, run-ui-ci

#734 Updated feature alias for all features.
  composer.json
  composer.lock
  src/Pyz/Zed/CategoryDataImport/Business/CategoryDataImportBusinessFactory.php
Labels: run-latest-ci

#735 FRW-10741 Agent MFA integration.
  composer.lock
  src/Pyz/Yves/AgentPage/Theme/default/components/molecules/agent-navigation/agent-navigation.twig
  src/Pyz/Yves/AgentPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/user-set-up-page/set-up-page.twig
Labels: improvement, run-ui-ci

#743 FRW-10759 Integrations and fixes.
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Yves/AgentPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/CustomerPage/Theme/default/templates/page-layout-login/page-layout-login.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/customer-set-up-page/customer-set-up-page.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/user-set-up-page/user-set-up-page.twig
  src/Pyz/Zed/Transfer/TransferConfig.php
Labels: bug, dependencies, run-latest-ci, run-functional-ci, run-static-ci, run-ui-ci

#744 CC-36096: Fixes security issue with node modules
  package-lock.json
Labels: run-static-ci, run-npm-ci

#745 Removed CustomerReorderWidget.
  composer.json
  composer.lock
  src/Pyz/Yves/CartReorderPage/Theme/default/components/molecules/cart-reorder-form/cart-reorder-form.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerPage/Theme/default/views/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/components/molecules/customer-reorder-form/customer-reorder-form.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/views/customer-reorder-bundle-item-checkbox/customer-reorder-bundle-item-checkbox.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/views/customer-reorder-item-checkbox/customer-reorder-item-checkbox.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/views/customer-reorder/customer-reorder.twig
Labels: run-ui-ci

#749 FRW-10742 Fixed duplicated requests during login.
  composer.json
  composer.lock
Labels: run-ui-ci

#746 FRW-10772 Fixed navigation from homepage.
  src/Pyz/Shared/CmsBlock/Theme/default/template/type_1_inspirational_block.twig
  src/Pyz/Shared/CmsBlock/Theme/default/template/type_2_inspirational_block.twig
  src/Pyz/Yves/ContentBannerWidget/Theme/default/components/molecules/banner-jumbotron/banner-jumbotron.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/customer-form/customer-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.twig
Labels: bug, run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-ui-ci

#748 CC-36086 OA. Yves. Order Total is not updated in the Order History table
  composer.json
  composer.lock
Labels: bug, run-latest-ci, run-ui-ci

#750 FRW-10776 Integration.
  composer.lock
Labels: bug, run-ui-ci

#752 FRW 10760 Fixed 404 error on filter by category in dynamic sale category
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
Labels: bug, run-latest-ci, run-ui-ci

#736 Release 202507.0
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  deploy.aop-b2c-testing.yml
  deploy.aop-consultant-b2c.yml
  deploy.aop-demoshop-b2c.yml
  deploy.scos2-b2c.yml
  deploy.spryker-dynamicstore.yml
  deploy.spryker-scosb2c.yml
  package-lock.json
  src/Pyz/Shared/CmsBlock/Theme/default/template/type_1_inspirational_block.twig
  src/Pyz/Shared/CmsBlock/Theme/default/template/type_2_inspirational_block.twig
  src/Pyz/Yves/AgentPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/CartReorderPage/Theme/default/components/molecules/cart-reorder-form/cart-reorder-form.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-card/category-card.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-list-item/category-list-item.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-links-list/suggestion-links-list.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-product/suggestion-product.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/view-mode-switch/view-mode-switch.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/templates/page-layout-order-submitted/page-layout-order-submitted.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/search-cms-results/search-cms-results.twig
  src/Pyz/Yves/ContentBannerWidget/Theme/default/components/molecules/banner-jumbotron/banner-jumbotron.twig
  src/Pyz/Yves/ContentProductWidget/Theme/default/views/cms-product-abstract-list-alternative/cms-product-abstract-list-alternative.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/customer-form/customer-form.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/customer-navigation/customer-navigation.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerPage/Theme/default/templates/page-layout-login/page-layout-login.twig
  src/Pyz/Yves/CustomerPage/Theme/default/views/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/components/molecules/customer-reorder-form/customer-reorder-form.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/views/customer-reorder-bundle-item-checkbox/customer-reorder-bundle-item-checkbox.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/views/customer-reorder-item-checkbox/customer-reorder-item-checkbox.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/views/customer-reorder/customer-reorder.twig
  src/Pyz/Yves/DiscountPromotionWidget/Theme/default/views/cart-discount-promotion-products-list/cart-discount-promotion-products-list.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/customer-set-up-page/customer-set-up-page.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/user-set-up-page/user-set-up-page.twig
  src/Pyz/Yves/ProductAlternativeWidget/Theme/default/views/wishlist-product-alternative/wishlist-product-alternative.twig
  src/Pyz/Yves/ProductComparisonPage/Theme/default/components/molecules/comparison-link/comparison-link.twig
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-configurator/product-configurator.twig
  src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
  src/Pyz/Yves/ProductGroupWidget/Theme/default/components/molecules/color-selector-pdp/color-selector-pdp.twig
  src/Pyz/Yves/ProductSetListPage/Theme/default/views/set-list/set-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/banner/banner.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-icon-list/navigation-icon-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-list/navigation-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-multilevel-node/navigation-multilevel-node.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card/product-card.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item-list/product-item-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item/product-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-list-item/product-list-item.twig
  src/Pyz/Yves/WishlistPage/Theme/default/components/molecules/wishlist-detail-table/wishlist-detail-table.twig
  src/Pyz/Zed/Transfer/TransferConfig.php
Labels: run-latest-ci, run-compatibility-ci

#755 FRW-10788 Updated cypress tests
  composer.lock
Labels: bug, run-ui-ci

#756 FRW-10788 Updated cypress tests
  composer.lock
Labels: bug, run-compatibility-ci
