Repository spryker-shop/b2c-demo-shop, pull requests merged in 2025-02, with the labels that each got.

#631 FRW-9711 Made CI test execution label-dependent.
  .github/workflows/ci.yml
  .github/workflows/enforce-labels.yml
  .github/workflows/robot-ui-e2e-tests.yml
  composer.lock
Labels: improvement, run-static-ci, run-npm-ci

#644 ACP-4696: integration
  composer.json
  composer.lock
  src/Orm/Zed/TaxApp/Persistence/SpyTaxIdValidationHistory.php
  src/Orm/Zed/TaxApp/Persistence/SpyTaxIdValidationHistoryQuery.php
  src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php
Labels: run-functional-ci, run-static-ci

#645 FRW-9083 Integration
  composer.json
  composer.lock
  data/import/common/AT/cms_block_store.csv
  data/import/common/DE/cms_block_store.csv
  data/import/common/US/cms_block_store.csv
  data/import/common/common/cms_block.csv
  data/import/common/common/glossary.csv
  package-lock.json
  src/Orm/Zed/CustomerDataChangeRequest/Persistence/SpyCustomerDataChangeRequest.php
  src/Orm/Zed/CustomerDataChangeRequest/Persistence/SpyCustomerDataChangeRequestQuery.php
  src/Pyz/Yves/LanguageSwitcherWidget/Theme/default/components/molecules/language-switcher/language-switcher.twig
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/search-form/search-form.twig
  src/Pyz/Zed/Customer/CustomerDependencyProvider.php
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
  src/Pyz/Zed/Mail/MailDependencyProvider.php
Labels: run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-static-ci, run-ui-ci
